# 站点配置
baseURL = "https://htext.top/"
# 标题
title = "Huanlan233's Texts"
# 语言编码
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
# 版权信息
copyright = "CC BY 4.0"

favicon = "static/favicon.ico"

# 主题选择
theme = "stack" 

# 主题设置
[params]
mainSections = ["posts"]
rssFullContent = true

    [params.footer]
    since = 2022
    customText = "苟延残喘的小博客"
    
    [params.sidebar]
    subtitle = "什么都会一点，什么都只会一点。"
    emoji = ""

        [params.sidebar.avatar]
        src = "img/avatar.png"

    [params.comments]
    enabled = true
    provider = "twikoo"

        [params.comments.twikoo]
        envId = "https://twikoo.api.htext.top"
        region = "window.location.pathname"
        path = ""
        lang = "zh"

    # 搜索小组件
    [[params.widgets.homepage]]
    type = "search"

    # 档案小组件
    [[params.widgets.homepage]]
    type = "archives"
        [params.widgets.homepage.params]
        limit = 5

    # 归档小组件
    [[params.widgets.homepage]]
    type = "categories"
        [params.widgets.homepage.params]
        limit = 10

    # 标签云小组件
    [[params.widgets.homepage]]
    type = "tag-cloud"
        [params.widgets.homepage.params]
        limit = 10

    # toc 小组件
    [[params.widgets.page]]
    type = "toc"

    [params.DateFormat]
    published = "2, Jan, 2006"
    lastUpdated = "2, Jan, 2006 15:04 MST"
